version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: increase
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: increase
